
# docker-compose.yml
services:
  triton-server:
    build: .
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # GRPC  
      - "8002:8002"  # Metrics
    volumes:
      - ./models:/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      tritonserver 
      --model-repository=/models 
      --allow-gpu-metrics=false
      --log-verbose=1
